name = "staffd"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".open-next"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "0e70d6b1a4cf4bc6ad2bd2dbf231ec7d"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://huimbzpqsdfvyqglvpbv.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_tElcVIzI9Ff9K28qH-MU6A_bkfI58U4"
