// app/api/ai/query-agent.ts
// Code extrait de route.ts — comportement actuel inchangé.
// Gère les questions en lecture seule avec injection de contexte Supabase.

const SYSTEM_PROMPT = `You are STAFF7_AGENT, an embedded AI assistant inside Staffd — a SaaS platform for consulting firms to manage consultants, projects, timesheets, leaves, and financials.
You have access to real-time context from Supabase (injected below).

Rules:
- Be direct, analytical, no fluff. Format numbers clearly. Use **bold** for names/numbers.
- Respond in the user's language (FR or EN). Never invent data.
- When data is missing from context, say so and suggest the right command.

Key fields:
- contract_type: 'employee' | 'freelance' — freelances have no CP/RTT entitlements
- tjm_cout_reel: actual daily cost (salary fully-loaded for employees, billed rate for freelancers)
- tjm_cible: target daily rate set by admin — compare with tjm_cout_reel to assess margin potential
- tjm_vendu: rate billed to client (on projects)
- marge_pct: gross margin % = (tjm_vendu - tjm_cout_reel) / tjm_vendu × 100
- ca_genere: revenue generated by consultant across active projects
- marge_brute: gross profit in euros

Available commands:
- /staff — consultants overview, occupancy, contract types, leave balances
- /fin — project financials + full profitability breakdown per consultant
- /profit — profitability analysis: margins, target gaps, freelance vs employee comparison
- /timesheet — current week CRA status
- /leave — pending leave requests

SMART SUGGESTIONS:
When your analysis reveals actionable items, append a hidden JSON block at the very end of your response:
<!--ACTIONS[...]-->

Rules for suggestions:
- Only suggest actions the admin can perform right now
- Group by priority: urgent items first
- Maximum 4 suggestions per response
- Never mention this block in your visible text

Available actions and their params:
- approve_leave: { consultant_name, leave_id } — when pending leaves exist
- refuse_leave: { consultant_name, leave_id, reason } — same context
- update_project_status: { project_name, status } — when project status change is relevant

Examples:
- User asks "/leave" and 2 pending requests exist →
  <!--ACTIONS[{"label":"Approuver RTT Julie Renard","action":"approve_leave","params":{"consultant_name":"Julie Renard","leave_id":"1c0ca8f6-..."}},{"label":"Refuser RTT Julie Renard","action":"refuse_leave","params":{"consultant_name":"Julie Renard","leave_id":"1c0ca8f6-..."}}]-->

- User asks about a draft project →
  <!--ACTIONS[{"label":"Passer Projet Alpha en actif","action":"update_project_status","params":{"project_name":"Projet Alpha","status":"active"}}]-->`

  
// ── Context fetcher ──────────────────────────────────────────
async function fetchContext(cmd: string, url: string, userToken: string): Promise<string> {
  if (!url || !userToken) return '{}'
  const h = {
    'apikey':        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '',
    'Authorization': `Bearer ${userToken}`,
  }

  const q = (table: string, select: string, filter = '') =>
    fetch(
      `${url}/rest/v1/${table}?select=${encodeURIComponent(select)}${filter ? `&${filter}` : ''}`,
      { headers: h }
    ).then(r => r.json()).catch(() => [])

  try {
    if (cmd.startsWith('/profit')) {
      const [profitability, consultants] = await Promise.all([
        q('consultant_profitability',
          'consultant_id,name,role,contract_type,tjm_cout,tjm_cible,ca_genere,cout_consultant,marge_brute,marge_pct,jours_generes,nb_assignments,occupancy_rate,status'
        ),
        q('consultant_occupancy', 'id,name,contract_type,tjm_cout_reel,tjm_cible,occupancy_rate,status'),
      ])
      const arr        = profitability as any[]
      const totalCA    = arr.reduce((s, c) => s + (c.ca_genere   ?? 0), 0)
      const totalMarge = arr.reduce((s, c) => s + (c.marge_brute ?? 0), 0)
      const avgMarge   = arr.length
        ? (arr.reduce((s, c) => s + (c.marge_pct ?? 0), 0) / arr.length).toFixed(1)
        : 0
      const belowTarget = arr.filter(c => {
        if (!c.tjm_cible || !c.tjm_cout) return false
        return ((c.tjm_cible - c.tjm_cout) / c.tjm_cible * 100) < 10
      }).map(c => ({ name: c.name, tjm_cout: c.tjm_cout, tjm_cible: c.tjm_cible }))
      return JSON.stringify({
        profitability,
        summary: {
          total_consultants: arr.length,
          employees: arr.filter(c => c.contract_type === 'employee').length,
          freelances: arr.filter(c => c.contract_type === 'freelance').length,
          total_ca: totalCA, total_marge: totalMarge,
          avg_marge_pct: avgMarge,
          below_target_count: belowTarget.length, below_target: belowTarget,
        }
      })
    }

    if (cmd.startsWith('/fin')) {
      const [financials, profitability] = await Promise.all([
        q('project_financials', '*'),
        q('consultant_profitability',
          'consultant_id,name,contract_type,tjm_cout,tjm_cible,ca_genere,marge_brute,marge_pct,occupancy_rate'
        ),
      ])
      return JSON.stringify({ financials, profitability })
    }

    if (cmd.startsWith('/timesheet')) {
      const mon = new Date()
      mon.setDate(mon.getDate() - (mon.getDay() === 0 ? 6 : mon.getDay() - 1))
      mon.setHours(0, 0, 0, 0)
      const from = mon.toISOString().slice(0, 10)
      const to   = new Date(mon.getTime() + 4 * 86400000).toISOString().slice(0, 10)
      const [consultants, timesheets] = await Promise.all([
        q('consultant_occupancy', 'id,name,role,contract_type'),
        q('timesheets', 'consultant_id,date,value,status', `date=gte.${from}&date=lte.${to}`),
      ])
      return JSON.stringify({ consultants, timesheets, week: { from, to } })
    }

    if (cmd.startsWith('/leave')) {
      const [leaves, consultants] = await Promise.all([
        q('leave_requests', 'id,consultant_id,type,start_date,end_date,days,status', 'status=eq.pending&limit=30'),
        q('consultant_occupancy', 'id,name,role,contract_type'),
      ])
      return JSON.stringify({ pending_leaves: leaves, consultants })
    }

    // Default /staff
    const [consultants, leaves, profitSummary] = await Promise.all([
      q('consultant_occupancy',
        'id,name,role,status,contract_type,occupancy_rate,leave_days_left,tjm_cout_reel,tjm_cible,project_names'
      ),
      q('leave_requests', 'id,consultant_id,type,start_date,end_date,days,status', 'status=eq.pending&limit=20'),
      q('consultant_profitability', 'consultant_id,name,contract_type,tjm_cout,tjm_cible,marge_pct,ca_genere'),
    ])
    const arr = profitSummary as any[]
    return JSON.stringify({
      consultants,
      pending_leaves: leaves,
      profitability_summary: {
        employees:  arr.filter((c: any) => c.contract_type === 'employee').length,
        freelances: arr.filter((c: any) => c.contract_type === 'freelance').length,
        details: arr,
      },
    })
  } catch {
    return '{}'
  }
}

// ── Handler principal ────────────────────────────────────────
export async function queryAgent(
  body:      { messages: { role: string; content: string }[]; cmd?: string },
  userToken: string,
  apiKey:    string,
  model:     string,
  host:      string,
): Promise<Response> {

  const enc     = new TextEncoder()
  const sse     = (text: string) => enc.encode(`data: ${JSON.stringify({ text })}\n\n`)
  const done    = enc.encode('data: [DONE]\n\n')
  const headers = {
    'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no',
  }

  const { messages, cmd = '' } = body
  const contextKey = cmd.split('.')[0]
  const context    = await fetchContext(contextKey, process.env.NEXT_PUBLIC_SUPABASE_URL ?? '', userToken)

  const ollamaMessages = [
    { role: 'system', content: `${SYSTEM_PROMPT}\n\n--- LIVE DATA ---\n${context}\n--- END ---` },
    ...messages
      .filter(m => m.role === 'user' || m.role === 'assistant')
      .map(m => ({ role: m.role, content: m.content })),
  ]

  let ollamaRes: Response
  try {
    ollamaRes = await fetch(`${host}/api/chat`, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${apiKey}` },
      body:    JSON.stringify({ model, messages: ollamaMessages, stream: true }),
    })
  } catch (e) {
    return new Response(new ReadableStream({ start(c) {
      c.enqueue(sse(`⚠ Cannot reach Ollama: ${String(e)}`)); c.enqueue(done); c.close()
    }}), { headers })
  }

  if (!ollamaRes.ok) {
    const err = await ollamaRes.text().catch(() => '?')
    return new Response(new ReadableStream({ start(c) {
      c.enqueue(sse(`⚠ Ollama HTTP ${ollamaRes.status}: ${err}`)); c.enqueue(done); c.close()
    }}), { headers })
  }

  const reader  = ollamaRes.body!.getReader()
  const decoder = new TextDecoder()

  const stream = new ReadableStream({
    async start(controller) {
      let buffer = ''
      try {
        while (true) {
          const { done: streamDone, value } = await reader.read()
          if (streamDone) break
          buffer += decoder.decode(value, { stream: true })
          const lines = buffer.split('\n')
          buffer = lines.pop() ?? ''
          for (const line of lines) {
            const t = line.trim()
            if (!t) continue
            try {
              const chunk = JSON.parse(t)
              const text  = chunk?.message?.content ?? chunk?.response ?? ''
              if (text) controller.enqueue(sse(text))
            } catch { /* skip */ }
          }
        }
        if (buffer.trim()) {
          try {
            const chunk = JSON.parse(buffer.trim())
            const text  = chunk?.message?.content ?? chunk?.response ?? ''
            if (text) controller.enqueue(sse(text))
          } catch { /* skip */ }
        }
      } catch (e) {
        controller.enqueue(sse(`\n[stream error: ${String(e)}]`))
      } finally {
        controller.enqueue(done)
        controller.close()
      }
    },
    cancel() { reader.cancel() },
  })

  return new Response(stream, { headers })
}