import type {
  Consultant, Project, LeaveRequest,
  KpiData, ActivityItem
} from '@/types'

export const CONSULTANTS: Consultant[] = [
  {
    id: 'am',
    name: 'Alice Martin',
    initials: 'AM',
    role: 'Lead Developer',
    status: 'assigned',
    avatarColor: 'green',
    currentProject: 'Alpha CRM',
    currentProjectId: 'alpha-crm',
    availableFrom: '2026-04-15',
    leaveDaysLeft: 18,
    occupancyRate: 90,
  },
  {
    id: 'bl',
    name: 'Baptiste Leroi',
    initials: 'BL',
    role: 'Data Engineer',
    status: 'available',
    avatarColor: 'cyan',
    currentProject: 'Nexus v2',
    currentProjectId: 'nexus-v2',
    availableFrom: undefined,
    leaveDaysLeft: 22,
    occupancyRate: 50,
  },
  {
    id: 'ck',
    name: 'Clara Kim',
    initials: 'CK',
    role: 'UX Designer',
    status: 'leave',
    avatarColor: 'pink',
    availableFrom: '2026-03-19',
    leaveDaysLeft: 7,
    occupancyRate: 0,
  },
  {
    id: 'dm',
    name: 'David Mora',
    initials: 'DM',
    role: 'DevOps Engineer',
    status: 'partial',
    avatarColor: 'gold',
    currentProject: 'Nexus v2',
    currentProjectId: 'nexus-v2',
    availableFrom: '2026-04-01',
    leaveDaysLeft: 12,
    occupancyRate: 50,
  },
  {
    id: 'ep',
    name: 'Emma Petit',
    initials: 'EP',
    role: 'Backend Developer',
    status: 'assigned',
    avatarColor: 'purple',
    currentProject: 'Alpha CRM',
    currentProjectId: 'alpha-crm',
    availableFrom: '2026-04-15',
    leaveDaysLeft: 25,
    occupancyRate: 100,
  },
]

export const PROJECTS: Project[] = [
  {
    id: 'alpha-crm',
    name: 'Alpha CRM',
    client: 'Accenture',
    consultantIds: ['am', 'bl', 'ep', 'dm'],
    progress: 72,
    endDate: '2026-04-15',
    status: 'active',
  },
  {
    id: 'nexus-v2',
    name: 'Nexus v2',
    client: 'BNP Paribas',
    consultantIds: ['dm', 'bl'],
    progress: 38,
    endDate: '2026-06-30',
    status: 'active',
  },
  {
    id: 'datalake',
    name: 'DataLake Refonte',
    client: 'Engie',
    consultantIds: ['ck', 'am', 'ep'],
    progress: 51,
    endDate: '2026-05-20',
    status: 'active',
  },
  {
    id: 'infra-k8s',
    name: 'Infra K8s',
    client: 'Société Générale',
    consultantIds: ['dm'],
    progress: 5,
    endDate: '2026-08-31',
    status: 'starting',
  },
]

export const LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr-1',
    consultantId: 'ck',
    consultantName: 'Clara Kim',
    type: 'CP',
    startDate: '2026-03-14',
    endDate: '2026-03-18',
    days: 5,
    status: 'pending',
    impactWarning: 'Projet DataLake affecté — 1 dev manquant semaine 11',
  },
  {
    id: 'lr-2',
    consultantId: 'dm',
    consultantName: 'David Mora',
    type: 'RTT',
    startDate: '2026-03-05',
    endDate: '2026-03-05',
    days: 1,
    status: 'pending',
  },
  {
    id: 'lr-3',
    consultantId: 'ep',
    consultantName: 'Emma Petit',
    type: 'CP',
    startDate: '2026-04-01',
    endDate: '2026-04-05',
    days: 5,
    status: 'pending',
  },
]

export const KPI: KpiData = {
  activeConsultants: 12,
  totalConsultants: 14,
  activeProjects: 6,
  pendingLeaves: 3,
  occupancyRate: 78,
}

export const ACTIVITY: ActivityItem[] = [
  {
    id: 'a1',
    type: 'leave',
    message: 'Clara Kim — demande de congé 14–18 mars',
    time: 'il y a 2h',
    read: false,
  },
  {
    id: 'a2',
    type: 'assignment',
    message: 'Baptiste Leroi affecté → Nexus v2',
    time: 'il y a 5h',
    read: false,
  },
  {
    id: 'a3',
    type: 'milestone',
    message: 'Projet Alpha CRM — jalon livré ✓',
    time: 'hier · 14:32',
    read: true,
  },
  {
    id: 'a4',
    type: 'alert',
    message: 'Fin de mission Emma Petit dans 12j',
    time: 'hier · alerte auto',
    read: true,
  },
]
